// Autentificación de Usuarios
export const VALIDAR_EMAIL = 'VALIDAR_EMAIL';
export const VALIDAR_PASSWORD = 'VALIDAR_PASSWORD';
export const EMAIL_SUCCESS = 'EMAIL_SUCCESS';
export const PASSWORD_SUCCESS = 'PASSWORD_SUCCESS';

// Alertas
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

// Registro de Usuarios
export const REGISTRO_EXITOSO_CARGANDO = 'REGISTRO_EXITOSO_CARGANDO';
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

// Imágenes
export const OBTENER_IMAGENES = 'OBTENER_IMAGENES'; 
export const OBTENER_IMAGENES_ERROR = 'OBTENER_IMAGENES_ERROR';
export const MODIFICAR_DIFICULTAD_PUNTOS_IMAGEN = 'MODIFICAR_DIFICULTAD_PUNTOS_IMAGEN';
export const MODIFICAR_DIFICULTAD_PUNTOS_IMAGEN_CARGANDO = 'MODIFICAR_DIFICULTAD_PUNTOS_IMAGEN_CARGANDO';
export const MODIFICAR_DIFICULTAD_PUNTOS_IMAGEN_ERROR = 'MODIFICAR_DIFICULTAD_PUNTOS_IMAGEN_ERROR';

// 4 Imágenes y una palabra
export const OBTENER_AHORCADOS = 'OBTENER_AHORCADOS'; 
export const OBTENER_AHORCADOS_ERROR = 'OBTENER_AHORCADOS_ERROR';
export const GUARDAR_AHORCADO = 'GUARDAR_AHORCADO';
export const GUARDAR_AHORCADO_CARGANDO = 'GUARDAR_AHORCADO_CARGANDO';
export const GUARDAR_AHORCADO_ERROR = 'GUARDAR_AHORCADO_ERROR';
export const OBTENER_AHORCADOS_POR_USUARIO = 'OBTENER_AHORCADOS_POR_USUARIO'; 
export const OBTENER_AHORCADOS_POR_USUARIO_ERROR = 'OBTENER_AHORCADOS_POR_USUARIO_ERROR';
export const ELIMINAR_AHORCADO = 'ELIMINAR_AHORCADO';
export const ELIMINAR_AHORCADO_CARGANDO = 'ELIMINAR_AHORCADO_CARGANDO';
export const ELIMINAR_AHORCADO_ERROR = 'ELIMINAR_AHORCADO_ERROR';
export const MODIFICAR_AHORCADO = 'MODIFICAR_AHORCADO';
export const MODIFICAR_AHORCADO_CARGANDO = 'MODIFICAR_AHORCADO_CARGANDO';
export const MODIFICAR_AHORCADO_ERROR = 'MODIFICAR_AHORCADO_ERROR';
export const HABILITAR_INHABILITAR_AHORCADO = 'HABILITAR_INHABILITAR_AHORCADO';
export const HABILITAR_INHABILITAR_AHORCADO_CARGANDO = 'HABILITAR_INHABILITAR_AHORCADO_CARGANDO';
export const HABILITAR_INHABILITAR_AHORCADO_ERROR = 'HABILITAR_INHABILITAR_AHORCADO_ERROR';
export const ELIMINAR_AHORCADO_DESDE_ADMIN = 'ELIMINAR_AHORCADO_DESDE_ADMIN';
export const ELIMINAR_AHORCADO_DESDE_ADMIN_CARGANDO = 'ELIMINAR_AHORCADO_DESDE_ADMIN_CARGANDO';
export const ELIMINAR_AHORCADO_DESDE_ADMIN_ERROR = 'ELIMINAR_AHORCADO_DESDE_ADMIN_ERROR';
export const MODIFICAR_DIFICULTAD_PUNTOS_AHORCADO = 'MODIFICAR_DIFICULTAD_PUNTOS_AHORCADO';
export const MODIFICAR_DIFICULTAD_PUNTOS_AHORCADO_CARGANDO = 'MODIFICAR_DIFICULTAD_PUNTOS_AHORCADO_CARGANDO';
export const MODIFICAR_DIFICULTAD_PUNTOS_AHORCADO_ERROR = 'MODIFICAR_DIFICULTAD_PUNTOS_AHORCADO_ERROR';

// Palabras
export const OBTENER_PALABRAS = 'OBTENER_PALABRAS';
export const OBTENER_PALABRAS_ERROR = 'OBTENER_PALABRAS_ERROR';
export const OBTENER_PALABRAS_POR_USUARIO = 'OBTENER_PALABRAS_POR_USUARIO';
export const OBTENER_PALABRAS_POR_USUARIO_ERROR = 'OBTENER_PALABRAS_POR_USUARIO_ERROR';
export const GUARDAR_PALABRA = 'GUARDAR_PALABRA';
export const GUARDAR_PALABRA_CARGANDO = 'GUARDAR_PALABRA_CARGANDO';
export const GUARDAR_PALABRA_ERROR = 'GUARDAR_PALABRA_ERROR';
export const MODIFICAR_PALABRA = 'MODIFICAR_PALABRA';
export const MODIFICAR_PALABRA_CARGANDO = 'MODIFICAR_PALABRA_CARGANDO';
export const MODIFICAR_PALABRA_ERROR = 'MODIFICAR_PALABRA_ERROR';
export const ELIMINAR_PALABRA = 'ELIMINAR_PALABRA';
export const ELIMINAR_PALABRA_CARGANDO = 'ELIMINAR_PALABRA_CARGANDO';
export const ELIMINAR_PALABRA_ERROR = 'ELIMINAR_PALABRA_ERROR';
export const HABILITAR_INHABILITAR_PALABRA = 'HABILITAR_INHABILITAR_PALABRA';
export const HABILITAR_INHABILITAR_PALABRA_CARGANDO = 'HABILITAR_INHABILITAR_PALABRA_CARGANDO';
export const HABILITAR_INHABILITAR_PALABRA_ERROR = 'HABILITAR_INHABILITAR_PALABRA_ERROR';
export const ELIMINAR_PALABRA_DESDE_ADMIN = 'ELIMINAR_PALABRA_DESDE_ADMIN';
export const ELIMINAR_PALABRA_DESDE_ADMIN_CARGANDO = 'ELIMINAR_PALABRA_DESDE_ADMIN_CARGANDO';
export const ELIMINAR_PALABRA_DESDE_ADMIN_ERROR = 'ELIMINAR_PALABRA_DESDE_ADMIN_ERROR';
export const MODIFICAR_DIFICULTAD_PUNTOS_PALABRA = 'MODIFICAR_DIFICULTAD_PUNTOS_PALABRA';
export const MODIFICAR_DIFICULTAD_PUNTOS_PALABRA_CARGANDO = 'MODIFICAR_DIFICULTAD_PUNTOS_PALABRA_CARGANDO';
export const MODIFICAR_DIFICULTAD_PUNTOS_PALABRA_ERROR = 'MODIFICAR_DIFICULTAD_PUNTOS_PALABRA_ERROR';

// Perfiles
export const OBTENER_TODOS_LOS_PERFILES = 'OBTENER_TODOS_LOS_PERFILES';
export const OBTENER_TODOS_LOS_PERFILES_ERROR = 'OBTENER_TODOS_LOS_PERFILES_ERROR';
export const OBTENER_PERFIL_USUARIO = 'OBTENER_PERFIL_USUARIO';
export const OBTENER_PERFIL_USUARIO_ERROR = 'OBTENER_PERFIL_USUARIO_ERROR'; 
export const ACTUALIZAR_PERFIL = 'ACTUALIZAR_PERFIL'; 
export const ACTUALIZAR_PERFIL_ERROR = 'ACTUALIZAR_PERFIL_ERROR'; 

// Categorías
export const OBTENER_CATEGORIAS = 'OBTENER_CATEGORIAS'; 
export const OBTENER_CATEGORIAS_ERROR = 'OBTENER_CATEGORIAS_ERROR'; 

// Ligas
export const OBTENER_DISTRIBUCION_LIGAS = 'OBTENER_DISTRIBUCION_LIGAS'; 
export const OBTENER_DISTRIBUCION_LIGAS_ERROR = 'OBTENER_DISTRIBUCION_LIGAS_ERROR'; 

// Niveles de los juegos
// Imágenes
export const OBTENER_IMAGENES_POR_USUARIO = 'OBTENER_IMAGENES_POR_USUARIO';
export const OBTENER_IMAGENES_POR_USUARIO_ERROR = 'OBTENER_IMAGENES_POR_USUARIO_ERROR';
export const OBTENER_NIVEL_IMAGENES_USUARIO = 'OBTENER_NIVEL_IMAGENES_USUARIO';
export const OBTENER_NIVEL_IMAGENES_USUARIO_ERROR = 'OBTENER_NIVEL_IMAGENES_USUARIO_ERROR';
export const GUARDAR_IMAGEN = 'GUARDAR_IMAGEN';
export const GUARDAR_IMAGEN_CARGANDO = 'GUARDAR_IMAGEN_CARGANDO';
export const GUARDAR_IMAGEN_ERROR = 'GUARDAR_IMAGEN_ERROR';
export const MODIFICAR_IMAGEN = 'MODIFICAR_IMAGEN';
export const MODIFICAR_IMAGEN_CARGANDO = 'MODIFICAR_IMAGEN_CARGANDO';
export const MODIFICAR_IMAGEN_ERROR = 'MODIFICAR_IMAGEN_ERROR';
export const ELIMINAR_IMAGEN = 'ELIMINAR_IMAGEN';
export const ELIMINAR_IMAGEN_CARGANDO = 'ELIMINAR_IMAGEN_CARGANDO';
export const ELIMINAR_IMAGEN_ERROR = 'ELIMINAR_IMAGEN_ERROR';
export const HABILITAR_INHABILITAR_IMAGEN = 'HABILITAR_INHABILITAR_IMAGEN';
export const HABILITAR_INHABILITAR_IMAGEN_CARGANDO = 'HABILITAR_INHABILITAR_IMAGEN_CARGANDO';
export const HABILITAR_INHABILITAR_IMAGEN_ERROR = 'HABILITAR_INHABILITAR_IMAGEN_ERROR';
export const ELIMINAR_IMAGEN_DESDE_ADMIN = 'ELIMINAR_IMAGEN_DESDE_ADMIN';
export const ELIMINAR_IMAGEN_DESDE_ADMIN_CARGANDO = 'ELIMINAR_IMAGEN_DESDE_ADMIN_CARGANDO';
export const ELIMINAR_IMAGEN_DESDE_ADMIN_ERROR = 'ELIMINAR_IMAGEN_DESDE_ADMIN_ERROR';

// Usuarios
export const OBTENER_DISTRIBUCION_EDADES_USUARIOS = 'OBTENER_DISTRIBUCION_EDADES_USUARIOS';
export const OBTENER_DISTRIBUCION_EDADES_USUARIOS_ERROR = 'OBTENER_DISTRIBUCION_EDADES_USUARIOS_ERROR';
export const MODIFICAR_USUARIO_CARGANDO = 'MODIFICAR_USUARIO_CARGANDO';
export const MODIFICAR_USUARIO = 'MODIFICAR_USUARIO';
export const MODIFICAR_USUARIO_ERROR = 'MODIFICAR_USUARIO_ERROR';
export const MODIFICAR_USUARIO_SALIR = 'MODIFICAR_USUARIO_SALIR';
export const OBTENER_USUARIOS = 'OBTENER_USUARIOS';
export const OBTENER_USUARIOS_ERROR = 'OBTENER_USUARIOS_ERROR';
export const MODIFICAR_USUARIO_ADMIN_BLOQUEO_CARGANDO = 'MODIFICAR_USUARIO_ADMIN_BLOQUEO_CARGANDO';
export const MODIFICAR_USUARIO_ADMIN_BLOQUEO = 'MODIFICAR_USUARIO_ADMIN_BLOQUEO';
export const MODIFICAR_USUARIO_ADMIN_BLOQUEO_ERROR = 'MODIFICAR_USUARIO_ADMIN_BLOQUEO_ERROR';
export const OBTENER_IMAGENES_POR_USUARIO_ADMIN = 'OBTENER_IMAGENES_POR_USUARIO_ADMIN';
export const OBTENER_IMAGENES_POR_USUARIO_ADMIN_CARGANDO = 'OBTENER_IMAGENES_POR_USUARIO_ADMIN_CARGANDO';
export const OBTENER_IMAGENES_POR_USUARIO_ADMIN_ERROR = 'OBTENER_IMAGENES_POR_USUARIO_ADMIN_ERROR';
export const OBTENER_PALABRAS_POR_USUARIO_ADMIN = 'OBTENER_PALABRAS_POR_USUARIO_ADMIN';
export const OBTENER_PALABRAS_POR_USUARIO_ADMIN_CARGANDO = 'OBTENER_PALABRAS_POR_USUARIO_ADMIN_CARGANDO';
export const OBTENER_PALABRAS_POR_USUARIO_ADMIN_ERROR = 'OBTENER_PALABRAS_POR_USUARIO_ADMIN_ERROR';
export const OBTENER_AHORCADOS_POR_USUARIO_ADMIN = 'OBTENER_AHORCADOS_POR_USUARIO_ADMIN';
export const OBTENER_AHORCADOS_POR_USUARIO_ADMIN_CARGANDO = 'OBTENER_AHORCADOS_POR_USUARIO_ADMIN_CARGANDO';
export const OBTENER_AHORCADOS_POR_USUARIO_ADMIN_ERROR = 'OBTENER_AHORCADOS_POR_USUARIO_ADMIN_ERROR';

// Formularios de Contacto
export const ENVIAR_FORMULARIO_DE_CONTACTO = 'ENVIAR_FORMULARIO_DE_CONTACTO';
export const ENVIAR_FORMULARIO_DE_CONTACTO_CARGANDO = 'ENVIAR_FORMULARIO_DE_CONTACTO_CARGANDO';
export const ENVIAR_FORMULARIO_DE_CONTACTO_ERROR = 'ENVIAR_FORMULARIO_DE_CONTACTO_ERROR';

// Etiquetado de Imágenes, Palabras y Ahorcados
// Imágenes
export const ETIQUETAR_IMAGEN = 'ETIQUETAR_IMAGEN';
export const ETIQUETAR_IMAGEN_ERROR = 'ETIQUETAR_IMAGEN_ERROR';
export const ETIQUETAR_PALABRA = 'ETIQUETAR_PALABRA';
export const ETIQUETAR_PALABRA_ERROR = 'ETIQUETAR_PALABRA_ERROR';
export const ETIQUETAR_CUATRO_IMAGENES = 'ETIQUETAR_CUATRO_IMAGENES';
export const ETIQUETAR_CUATRO_IMAGENES_ERROR = 'ETIQUETAR_CUATRO_IMAGENES_ERROR';
export const OBTENER_IMAGENES_ETIQUETADAS = 'OBTENER_IMAGENES_ETIQUETADAS';
export const OBTENER_IMAGENES_ETIQUETADAS_CARGANDO = 'OBTENER_IMAGENES_ETIQUETADAS_CARGANDO';
export const OBTENER_IMAGENES_ETIQUETADAS_ERROR = 'OBTENER_IMAGENES_ETIQUETADAS_ERROR';
export const ELIMINAR_ETIQUETAS_IMAGENES = 'ELIMINAR_ETIQUETAS_IMAGENES';
export const ELIMINAR_ETIQUETAS_IMAGENES_CARGANDO = 'ELIMINAR_ETIQUETAS_IMAGENES_CARGANDO';
export const ELIMINAR_ETIQUETAS_IMAGENES_ERROR = 'ELIMINAR_ETIQUETAS_IMAGENES_ERROR';

// Palabras
export const OBTENER_PALABRAS_ETIQUETADAS = 'OBTENER_PALABRAS_ETIQUETADAS';
export const OBTENER_PALABRAS_ETIQUETADAS_CARGANDO = 'OBTENER_PALABRAS_ETIQUETADAS_CARGANDO';
export const OBTENER_PALABRAS_ETIQUETADAS_ERROR = 'OBTENER_PALABRAS_ETIQUETADAS_ERROR';
export const ELIMINAR_ETIQUETAS_PALABRAS = 'ELIMINAR_ETIQUETAS_PALABRAS';
export const ELIMINAR_ETIQUETAS_PALABRAS_CARGANDO = 'ELIMINAR_ETIQUETAS_PALABRAS_CARGANDO';
export const ELIMINAR_ETIQUETAS_PALABRAS_ERROR = 'ELIMINAR_ETIQUETAS_PALABRAS_ERROR';

// Ahorcados
export const ETIQUETAR_AHORCADO = 'ETIQUETAR_AHORCADO';
export const ETIQUETAR_AHORCADO_ERROR = 'ETIQUETAR_AHORCADO_ERROR';
export const OBTENER_AHORCADOS_ETIQUETADOS = 'OBTENER_AHORCADOS_ETIQUETADOS';
export const OBTENER_AHORCADOS_ETIQUETADOS_CARGANDO = 'OBTENER_AHORCADOS_ETIQUETADOS_CARGANDO';
export const OBTENER_AHORCADOS_ETIQUETADOS_ERROR = 'OBTENER_AHORCADOS_ETIQUETADOS_ERROR';
export const ELIMINAR_ETIQUETAS_AHORCADOS = 'ELIMINAR_ETIQUETAS_AHORCADOS';
export const ELIMINAR_ETIQUETAS_AHORCADOS_CARGANDO = 'ELIMINAR_ETIQUETAS_AHORCADOS_CARGANDO';
export const ELIMINAR_ETIQUETAS_AHORCADOS_ERROR = 'ELIMINAR_ETIQUETAS_AHORCADOS_ERROR';
