// Autentificación de Usuarios
export const VALIDAR_EMAIL = 'VALIDAR_EMAIL';
export const VALIDAR_PASSWORD = 'VALIDAR_PASSWORD';
export const EMAIL_SUCCESS = 'EMAIL_SUCCESS';
export const PASSWORD_SUCCESS = 'PASSWORD_SUCCESS';

// Alertas
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

// Registro de Usuarios
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

// Imágenes
export const OBTENER_IMAGENES = 'OBTENER_IMAGENES'; 
export const OBTENER_IMAGENES_ERROR = 'OBTENER_IMAGENES_ERROR'; 

// Palabras
export const OBTENER_PALABRAS = 'OBTENER_PALABRAS'; 
export const OBTENER_PALABRAS_ERROR = 'OBTENER_PALABRAS_ERROR'; 

// Perfiles
export const OBTENER_PERFIL_USUARIO = 'OBTENER_PERFIL_USUARIO'; 
export const OBTENER_PERFIL_USUARIO_ERROR = 'OBTENER_PERFIL_USUARIO_ERROR'; 
export const ACTUALIZAR_PERFIL = 'ACTUALIZAR_PERFIL'; 
export const ACTUALIZAR_PERFIL_ERROR = 'ACTUALIZAR_PERFIL_ERROR'; 

// Categorías
export const OBTENER_CATEGORIAS = 'OBTENER_CATEGORIAS'; 
export const OBTENER_CATEGORIAS_ERROR = 'OBTENER_CATEGORIAS_ERROR'; 

// Ligas
export const OBTENER_DISTRIBUCION_LIGAS = 'OBTENER_DISTRIBUCION_LIGAS'; 
export const OBTENER_DISTRIBUCION_LIGAS_ERROR = 'OBTENER_DISTRIBUCION_LIGAS_ERROR'; 

// Niveles de los juegos
// Imágenes
export const OBTENER_NIVEL_IMAGENES_USUARIO = 'OBTENER_NIVEL_IMAGENES_USUARIO'; 
export const OBTENER_NIVEL_IMAGENES_USUARIO_ERROR = 'OBTENER_NIVEL_IMAGENES_USUARIO_ERROR'; 

// Etiquetado de Imágenes, Palabras y 4Imágenes
// imágenes
export const ETIQUETAR_IMAGEN = 'ETIQUETAR_IMAGEN';
export const ETIQUETAR_IMAGEN_ERROR = 'ETIQUETAR_IMAGEN_ERROR';
export const ETIQUETAR_PALABRA = 'ETIQUETAR_PALABRA';
export const ETIQUETAR_PALABRA_ERROR = 'ETIQUETAR_PALABRA_ERROR';
export const ETIQUETAR_CUATRO_IMAGENES = 'ETIQUETAR_CUATRO_IMAGENES';
export const ETIQUETAR_CUATRO_IMAGENES_ERROR = 'ETIQUETAR_CUATRO_IMAGENES_ERROR';
