export const VALIDAR_EMAIL = 'VALIDAR_EMAIL';
export const VALIDAR_PASSWORD = 'VALIDAR_PASSWORD';
export const EMAIL_SUCCESS = 'EMAIL_SUCCESS';
export const PASSWORD_SUCCESS = 'PASSWORD_SUCCESS';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

// Imágenes
export const OBTENER_IMAGENES = 'OBTENER_IMAGENES'; 
export const OBTENER_IMAGENES_ERROR = 'OBTENER_IMAGENES_ERROR'; 

